# TCL File Generated by Component Editor 9.1sp2
# Tue Nov 19 20:52:09 EST 2013
# DO NOT MODIFY


# +-----------------------------------
# | 
# | custominstruction "custominstruction" v1.0
# | null 2013.11.19.20:52:09
# | 
# | 
# | F:/My Documents/Desktop/hw8a/custominstruction.vhd
# | 
# |    ./custominstruction.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module custominstruction
# | 
set_module_property NAME custominstruction
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP ""
set_module_property DISPLAY_NAME custominstruction
set_module_property TOP_LEVEL_HDL_FILE custominstruction.vhd
set_module_property TOP_LEVEL_HDL_MODULE custominstruction
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file custominstruction.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point nios_custom_instruction_slave_0
# | 
add_interface nios_custom_instruction_slave_0 nios_custom_instruction end
set_interface_property nios_custom_instruction_slave_0 clockCycle 0
set_interface_property nios_custom_instruction_slave_0 operands 2

set_interface_property nios_custom_instruction_slave_0 ENABLED true

add_interface_port nios_custom_instruction_slave_0 dataa dataa Input 32
add_interface_port nios_custom_instruction_slave_0 datab datab Input 32
add_interface_port nios_custom_instruction_slave_0 result result Output 32
# | 
# +-----------------------------------
